- hosts: all
  become: true
  become_user: root

  vars_files:
    - pass.yml

  tasks:
  - name: Install prerequisites
    shell: |
      apt-get install \
      apt-transport-https \
      ca-certificates \
      curl \
      gnupg-agent \
      software-properties-common --assume-yes
  - name: Add Docker GPG key
    shell: |
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - name: Add Docker repo
    shell: |
      add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) \
      stable"

  - name: Update package list
    ignore_errors: yes
    shell: |
      apt-get update

  - name: Install Docker CE Service
    shell: |
      apt-get install docker-ce docker-ce-cli containerd.io --assume-yes
  - name: Create container syslog logging
    shell:
      cd /etc/docker && touch daemon.json
      
  - name: Enable container syslog logging  
    copy:
      dest: /etc/docker/daemon.json
      content: |
        {
          "log-driver": "syslog"
        }
